title: Prof. Joohee Lee
description: Welcome to SSWU Crypto LAB!
theme: just-the-docs

url: https://sungshincrypto.github.io/
baseurl : /sungshincrypto.github.io

style_css:
- assets/css/style.css

favicon_ico : "gallery/favicon.ico"

color_schme: dark

aux_links:
  "SungshinCrypto on GitHub":
    - "https://github.com/sungshincrypto/sungshincrypto.github.io"

