title: SungshinCrypto
description: Welcome to SSWU Crypto LAB!
theme: just-the-docs

url: https://sungshincrypto.github.io/

include:
  - custom.css

aux_links:
  "SungshinCrypto on GitHub":
    - "https://github.com/sungshincrypto/sungshincrypto.github.io"

